apiVersion: v1
kind: Service
metadata:
  name: container-self-service
  namespace: default
  labels:
    app: container-self-service
    owner: Manasi-Belhe
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: container-self-service