apiVersion: v1
kind: Service
metadata:
  name: container-self-service
  namespace: default
  labels:
    app: container-self-service
    techcontact: manasibelhe@gmail.com
    owner: Manasi Belhe
spec:
  ports:
  - port: 4001
    targetPort: 4001
    protocol: TCP
  selector:
    app: container-self-service