apiVersion: v1
kind: Service
metadata:
  name: container-self-service
  namespace: default
  labels:
    app: container-self-service
    techcontact: $$uid$$
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer
  selector:
    app: container-self-service